# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Check Spearman correlations between interactions in X and treatment
#' 
#' @param treat A vector of outcomes.
#' @param X A matrix of spline bases.
#' @param inter.schedule An interaction schedule.
#' @param one_to_n A vector of length 1:length(treat).
#' @export
NULL

#' Create a basis vector
#' 
#' @param matvec A single integer.
#' @param resvec A single integer.
#' @param onesvec A single integer.
#' @param theta A single integer.
#' @export
basis_rcpp <- function(matvec, resvec, onesvec, theta) {
    .Call('_PLCE_basis_rcpp', PACKAGE = 'PLCE', matvec, resvec, onesvec, theta)
}

#' Create a basis vector but without making a kernel matrix
#' 
#' @param matvec A single integer.
#' @param resvec A single integer.
#' @param onesvec A single integer.
#' @param theta A single integer.
#' @export
basisvec_rcpp <- function(matvec, resvec, onesvec, theta) {
    .Call('_PLCE_basisvec_rcpp', PACKAGE = 'PLCE', matvec, resvec, onesvec, theta)
}

corbases <- function(treat, X, inter_schedule, one_to_n) {
    .Call('_PLCE_corbases', PACKAGE = 'PLCE', treat, X, inter_schedule, one_to_n)
}

#' Check Spearman correlations between interactions in X and treatment
#' 
#' @param y A vector of outcomes.
#' @param X A matrix of spline bases.
#' @param alpha.schedule The prior on lambda
#' @export
NULL

bayesLasso <- function(y, X, alpha) {
    .Call('_PLCE_bayesLasso', PACKAGE = 'PLCE', y, X, alpha)
}

#' Fast partialing out using weighted least squares
#' 
#' @param X A single integer.
#' @param y A single integer.
#' @param w A single integer.
#' @export
fastres_cpp <- function(X, y, w) {
    .Call('_PLCE_fastres_cpp', PACKAGE = 'PLCE', X, y, w)
}

rcppClamp <- function(x, mi, ma) {
    .Call('_PLCE_rcppClamp', PACKAGE = 'PLCE', x, mi, ma)
}

which_maxCpp <- function(v) {
    .Call('_PLCE_which_maxCpp', PACKAGE = 'PLCE', v)
}

arma_var <- function(v1) {
    .Call('_PLCE_arma_var', PACKAGE = 'PLCE', v1)
}

arma_matvar <- function(v1) {
    .Call('_PLCE_arma_matvar', PACKAGE = 'PLCE', v1)
}

arma_ginv <- function(v1) {
    .Call('_PLCE_arma_ginv', PACKAGE = 'PLCE', v1)
}

arma_symm <- function(v1) {
    .Call('_PLCE_arma_symm', PACKAGE = 'PLCE', v1)
}

#' Update beta
#' 
#' @export
solve_cpp <- function(XpX, Xpy) {
    .Call('_PLCE_solve_cpp', PACKAGE = 'PLCE', XpX, Xpy)
}

#' Armadillo Standard Deviation
#' 
#' @export
sd_cpp <- function(v1) {
    .Call('_PLCE_sd_cpp', PACKAGE = 'PLCE', v1)
}

#' Armadillo Median
#' 
#' @export
median_cpp <- function(v1) {
    .Call('_PLCE_median_cpp', PACKAGE = 'PLCE', v1)
}

